package test;

import Main;
import Std.parseInt;

using Lambda;
using StringTools;
using buddy.Should;

@:access(Main)
class TestProcess extends buddy.BuddySuite {
	
	public function new() {
		
		describe( "Test getOffsets", {
			
			it( "no offsets length 0", {
				Main.getOffsets( "abcdefg", "h", 0 ).length.should.be( 0 );
			});
			
			it( "offset 0 length 1", {
				Main.getOffsets( "abcdefg", "a", 0 ).length.should.be( 1 );
			});

			it( "offset 0", {
				Main.getOffsets( "abcdefg", "a", 0 )[0].should.be( 0 );
			});

			it( "offset 1", {
				Main.getOffsets( "abcdefg", "b", 0 )[0].should.be( 1 );
			});

		});
		
		describe( "Test constructSolution", {
			
			it( "Simple", {
				Main.constructSolution( "somewackyrunesatouristfound", "secret".length, 0, 3 ).should.be( "SomEwaCkyRunEsaT" );
			});
			it( "Where to begin", {
				Main.constructSolution(
					Main.clean( "ther tis nobler in the mind to suffer The slings and arrows of outrageous fortune Or to take arms against a sea of troubles And by opposing end them To die to sleep No more and by a sleep to say we end The heartache and the thousand natural shocks That flesh is heir to" ),
					"trust".length, 0, 29 ).should.be( "ThertisnoblerinthemindtosuffeRtheslingsandarrowsofoutrageoUsfortuneortotakearmsagainstaSeaoftroublesandbyopposingendT" );
			});
			
		});
		
		describe( "Test process", {
			it( "Simple1", {
				final ip = simple1;
				Main.process( ip.text, ip.words ).should.be( "SomEwaCkyRunEsaT" );
			});
			it( "Simple1 offset", {
				final ip = simple1Offset;
				Main.process( ip.text, ip.words ).should.be( "SomEwaCkyRunEsaT" );
			});
			it( "Simple", {
				final ip = simple;
				Main.process( ip.text, ip.words ).should.be( "SomEwaCkyRunEsaT" );
			});
			it( "Where to begin1", {
				final ip = whereToBegin1;
				Main.process( ip.text, ip.words ).should.be( "ThertisnoblerinthemindtosuffeRtheslingsandarrowsofoutrageoUsfortuneortotakearmsagainstaSeaoftroublesandbyopposingendT" );
			});
			it( "Where to begin", {
				final ip = whereToBegin;
				Main.process( ip.text, ip.words ).should.be( "ThertisnoblerinthemindtosuffeRtheslingsandarrowsofoutrageoUsfortuneortotakearmsagainstaSeaoftroublesandbyopposingendT" );
			});
			it( "Be punctual", {
				final ip = bePunctual;
				Main.process( ip.text, ip.words ).should.be( "ErskeeperandthefinderofLostchildrenandiwillstrIkedownupontheewithgreaTvengeanceandfuriousangE" );
			});
			it( "Tempus fugit", {
				final ip = tempusFugit;
				Main.process( ip.text, ip.words ).should.be( "IpiscingeLitnullamLonefficiUtrquamegMtullamcoIpervelitNuspendisAesedmaleTuadadiamI" );
			});
			it( "I Have No Mouth", {
				final ip = iHaveNoMouth;
				Main.process( ip.text, ip.words ).should.be( "HaEaLaP" );
			});
			
		});
			
	}

	static function parseInput( input:String ) {
		final lines = input.replace( "\t", "" ).replace( "\r", "" ).split( "\n" );
		final text = lines[0];
		final words = lines.slice( 2 );
		return { text: text, words: words };
	}
	
	static function parseResult( input:String ) {
		return input.replace( "\t", "" ).replace( "\r", "" );
	}

	final simple1 = parseInput(
		"some wacky runes a tourist found
		1
		secret"
	);

	final simple1Offset = parseInput(
		"xxxsome wacky runes a tourist found
		1
		secret"
	);

	final simple = parseInput(
		"some wacky runes a tourist found
		4
		secret
		hidden
		invisible
		message"
	);

	final whereToBegin1 = parseInput(
		"To be or not to be that is the question Whether tis nobler in the mind to suffer The slings and arrows of outrageous fortune Or to take arms against a sea of troubles And by opposing end them To die to sleep No more and by a sleep to say we end The heartache and the thousand natural shocks That flesh is heir to
		1
		trust"
	);

	final whereToBegin = parseInput(
		"To be or not to be that is the question Whether tis nobler in the mind to suffer The slings and arrows of outrageous fortune Or to take arms against a sea of troubles And by opposing end them To die to sleep No more and by a sleep to say we end The heartache and the thousand natural shocks That flesh is heir to
		7
		aliens
		conspiracy
		theory
		resistance
		trust
		power
		corrupt"
	);

	final bePunctual = parseInput(
		"Blessed is he, who in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper - and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy my brothers.
		28
		secret
		hidden
		invisible
		message
		obfuscate
		clandestine
		aliens
		conspiracy
		theory
		resistance
		power
		corrupt
		iron
		rule
		pestilence
		plague
		waste
		trust
		elite
		illuminati
		privileged
		birth
		senate
		dictator
		caesar
		king
		citizen
		sheep"
	);

	final tempusFugit = parseInput(
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam lon efficiutr quam, egmt ullamcoiper velit. Nuspendisae sed maletuada diam. Ionec eu ex eu sem eleifend viverra. In risus metus, pharetra quis hendrerit non, elementum sit amet neque. Praesent lacus diam, pulvinar id ipsum a, ultricies elementum lectus. Integer malesuada quam ut ex lobortis tristique. Duis sit amet sapien non nisl tempus ullamcorper. Fusce feugiat nulla nulla, id ultrices tortor tempus a. Nam volutpat dui justo. Curabitur sed erat ac augue sagittis tempor. Integer felis purus, molestie a luctus a, consectetur sed eros. Curabitur dolor urna, congue eget odio sed, faucibus vestibulum lacus.
		1039
		aardvarks
		aardwolves
		abandon
		ability
		abroad
		absence
		absolute
		absolutely
		absorb
		academic
		accept
		access
		accident
		accompany
		accomplish
		according
		account
		accurate
		accuse
		achieve
		achievement
		acknowledge
		acquire
		across
		action
		active
		activist
		activity
		actress
		actual
		actually
		addition
		additional
		address
		adequate
		adjust
		adjustment
		administration
		administrator
		admire
		admission
		adolescent
		advance
		advanced
		advantage
		adventure
		advertising
		advice
		advise
		adviser
		advocate
		affair
		affect
		afford
		afraid
		afternoon
		agency
		agenda
		aggressive
		agreement
		agricultural
		aircraft
		airline
		airport
		alcohol
		aliens
		alliance
		almost
		already
		alternative
		although
		always
		amazing
		amount
		analysis
		analyst
		analyze
		ancient
		animal
		anniversary
		announce
		annual
		another
		answer
		anticipate
		anxiety
		anybody
		anymore
		anyone
		anything
		anyway
		anywhere
		apartment
		apparent
		apparently
		appeal
		appearance
		application
		appoint
		appointment
		appreciate
		approach
		appropriate
		approval
		approve
		approximately
		architect
		argument
		around
		arrange
		arrangement
		arrest
		arrival
		arrive
		article
		artist
		artistic
		aspect
		assault
		assert
		assess
		assessment
		assign
		assignment
		assist
		assistance
		assistant
		associate
		association
		assume
		assumption
		assure
		athlete
		athletic
		atmosphere
		attach
		attack
		attend
		attention
		attitude
		attorney
		attract
		attractive
		attribute
		audience
		author
		authority
		available
		average
		awareness
		background
		balance
		barely
		barrel
		barrier
		baseball
		basically
		basket
		basketball
		bathroom
		battery
		battle
		beautiful
		beauty
		because
		become
		bedroom
		before
		beginning
		behavior
		behind
		belief
		believe
		belong
		beneath
		benefit
		better
		between
		beyond
		billion
		biological
		birth
		birthday
		blanket
		bombing
		border
		borrow
		bother
		bottle
		bottom
		boundary
		boyfriend
		branch
		breakfast
		breast
		breath
		breathe
		bridge
		briefly
		brilliant
		broken
		budget
		building
		bullet
		burden
		business
		butter
		button
		cabinet
		caesar
		calculate
		camera
		campaign
		campus
		cancer
		candidate
		capability
		capable
		capacity
		capital
		captain
		capture
		carbon
		career
		careful
		carefully
		carrier
		category
		ceiling
		celebrate
		celebration
		celebrity
		center
		central
		century
		ceremony
		certain
		certainly
		chairman
		challenge
		chamber
		champion
		championship
		chance
		change
		changing
		channel
		chapter
		character
		characteristic
		characterize
		charge
		cheese
		chemical
		chicken
		childhood
		chocolate
		choice
		cholesterol
		choose
		church
		cigarette
		circle
		circumstance
		citizen
		civilian
		clandestine
		classic
		classroom
		clearly
		client
		climate
		clinic
		clinical
		closely
		closer
		clothes
		clothing
		cluster
		coalition
		coffee
		cognitive
		collapse
		colleague
		collect
		collection
		collective
		college
		colonial
		column
		combination
		combine
		comedy
		comfort
		comfortable
		commander
		comment
		commercial
		commission
		commit
		commitment
		committee
		common
		communicate
		communication
		community
		company
		compare
		comparison
		compete
		competition
		competitive
		competitor
		complain
		complaint
		complete
		completely
		complex
		complicated
		component
		compose
		composition
		comprehensive
		computer
		concentrate
		concentration
		concept
		concern
		concerned
		concert
		conclude
		conclusion
		concrete
		condition
		conduct
		conference
		confidence
		confident
		confirm
		conflict
		confront
		confusion
		congressional
		connect
		connection
		consciousness
		consensus
		consequence
		conservative
		consider
		considerable
		consideration
		consist
		consistent
		conspiracy
		constant
		constantly
		constitute
		constitutional
		construct
		construction
		consultant
		consume
		consumer
		consumption
		contact
		contain
		container
		contemporary
		content
		contest
		context
		continue
		continued
		contract
		contrast
		contribute
		contribution
		control
		controversial
		controversy
		convention
		conventional
		conversation
		convert
		conviction
		convince
		cookie
		cooking
		cooperation
		corner
		corporate
		corporation
		correct
		correspondent
		corrupt
		cotton
		council
		counselor
		counter
		country
		county
		couple
		courage
		course
		cousin
		coverage
		create
		creation
		creative
		creature
		credit
		criminal
		crisis
		criteria
		critic
		critical
		criticism
		criticize
		crucial
		cultural
		culture
		curious
		current
		currently
		curriculum
		custom
		customer
		damage
		danger
		dangerous
		daughter
		dealer
		debate
		decade
		decide
		decision
		declare
		decline
		decrease
		deeply
		defeat
		defend
		defendant
		defense
		defensive
		deficit
		define
		definitely
		definition
		degree
		deliver
		delivery
		demand
		democracy
		democratic
		demonstrate
		demonstration
		department
		depend
		dependent
		depending
		depict
		depression
		deputy
		derive
		describe
		description
		deserve
		design
		designer
		desire
		desperate
		despite
		destruction
		detail
		detailed
		detect
		determine
		develop
		developing
		development
		device
		devote
		dialogue
		dictator
		differ
		difference
		different
		differently
		difficult
		difficulty
		digital
		dimension
		dining
		dinner
		direct
		direction
		directly
		director
		disability
		disagree
		disappear
		disaster
		discipline
		discourse
		discover
		discovery
		discrimination
		discuss
		discussion
		disease
		dismiss
		disorder
		display
		dispute
		distance
		distant
		distinct
		distinction
		distinguish
		distribute
		distribution
		district
		diverse
		diversity
		divide
		division
		divorce
		doctor
		document
		domestic
		dominant
		dominate
		double
		downtown
		dramatic
		dramatically
		drawing
		driver
		during
		emit
		earnings
		easily
		eastern
		economic
		economics
		economist
		economy
		edition
		editor
		educate
		education
		educational
		educator
		effect
		effective
		effectively
		efficiency
		efficient
		effort
		either
		elderly
		election
		electric
		electricity
		electronic
		element
		elementary
		eliminate
		elite
		elsewhere
		embrace
		emerge
		emergency
		emission
		emotion
		emotional
		emphasis
		emphasize
		employ
		employee
		employer
		employment
		enable
		encounter
		encourage
		energy
		enforcement
		engage
		engine
		engineer
		engineering
		enhance
		enormous
		enough
		ensure
		enterprise
		entertainment
		entire
		entirely
		entrance
		environment
		environmental
		episode
		equally
		equipment
		escape
		especially
		essential
		essentially
		establish
		establishment
		estate
		estimate
		ethics
		ethnic
		evaluate
		evaluation
		evening
		eventually
		everybody
		everyday
		everyone
		everything
		everywhere
		evidence
		evolution
		evolve
		exactly
		examination
		examine
		example
		exceed
		excellent
		except
		exception
		exchange
		exciting
		executive
		exercise
		exhibit
		exhibition
		existence
		existing
		expand
		expansion
		expect
		expectation
		expense
		expensive
		experience
		experiment
		expert
		explain
		explanation
		explode
		explore
		explosion
		expose
		exposure
		express
		expression
		extend
		extension
		extensive
		extent
		external
		extraordinary
		extreme
		extremely
		fabric
		facility
		factor
		factory
		faculty
		failure
		fairly
		familiar
		family
		famous
		fantasy
		farmer
		fashion
		father
		favorite
		feature
		federal
		feeling
		fellow
		fiction
		fifteen
		fighter
		fighting
		figure
		finally
		finance
		financial
		finding
		finger
		finish
		fishing
		fitness
		flavor
		flight
		flower
		follow
		following
		football
		foreign
		forever
		forget
		formal
		formation
		former
		formula
		forward
		foundation
		founder
		fourth
		framework
		freedom
		freeze
		frequency
		frequent
		frequently
		friend
		friendly
		friendship
		frustration
		function
		fundamental
		funding
		funeral
		furniture
		furthermore
		future
		galaxy
		gallery
		garage
		garden
		garlic
		gather
		gender
		general
		generally
		generate
		generation
		genetic
		gentleman
		gently
		gesture
		gifted
		girlfriend
		glance
		global
		golden
		government
		governor
		gradually
		graduate
		grandfather
		grandmother
		greatest
		grocery
		ground
		growing
		growth
		guarantee
		guideline
		guilty
		habitat
		handful
		handle
		happen
		hardly
		headline
		headquarters
		health
		healthy
		hearing
		heaven
		heavily
		height
		helicopter
		helpful
		heritage
		herself
		hidden
		highlight
		highly
		highway
		himself
		historian
		historic
		historical
		history
		holiday
		homeless
		honest
		horizon
		horror
		hospital
		household
		housing
		however
		hundred
		hungry
		hunter
		hunting
		husband
		hypothesis
		identification
		identify
		identity
		ignore
		illegal
		illness
		illuminati
		illustrate
		imagination
		imagine
		immediate
		immediately
		immigrant
		immigration
		impact
		implement
		implication
		importance
		important
		impose
		impossible
		impress
		impression
		impressive
		improve
		improvement
		incentive
		incident
		include
		including
		income
		incorporate
		increase
		increased
		increasing
		increasingly
		incredible
		indeed
		independence
		independent
		indicate
		indication
		individual
		industrial
		industry
		infant
		infection
		inflation
		influence
		inform
		information
		ingredient
		initial
		initially
		initiative
		injury
		innocent
		inquiry
		inside
		insight
		insist
		inspire
		install
		instance
		instead
		institution
		institutional
		instruction
		instructor
		instrument
		insurance
		intellectual
		intelligence
		intend
		intense
		intensity
		intention
		interaction
		interest
		interested
		interesting
		internal
		international
		interpret
		interpretation
		intervention
		interview
		introduce
		introduction
		invasion
		invest
		investigate
		investigation
		investigator
		investment
		investor
		invite
		involve
		involved
		involvement
		iron
		island
		itself
		jacket
		journal
		journalist
		journey
		judgment
		junior
		justice
		justify
		killer
		killing
		king
		kitchen
		knowledge
		laboratory
		landscape
		language
		largely
		latter
		launch
		lawsuit
		lawyer
		leader
		leadership
		leading
		league
		learning
		leather
		legacy
		legend
		legislation
		legitimate
		length
		lesson
		letter
		liberal
		library
		license
		lifestyle
		lifetime
		likely
		limitation
		limited
		listen
		literally
		literary
		literature
		little
		living
		locate
		location
		long-term
		lovely
		secret
		senate
		trust
		valuable
		variable
		variation
		variety
		various
		vegetable
		vehicle
		venture
		version
		versus
		vessel
		veteran
		victim
		victory
		viewer
		village
		violate
		violation
		violence
		violent
		virtually
		virtue
		visible
		vision
		visitor
		visual
		volume
		volunteer
		vulnerable
		wander
		warning
		waste
		wealth
		wealthy
		weapon
		weather
		wedding
		weekend
		weekly
		weight
		welcome
		welfare
		western
		whatever
		whenever
		whereas
		whisper
		widely
		widespread
		willing
		window
		winner
		winter
		wisdom
		withdraw
		within
		without
		witness
		wonder
		wonderful
		wooden
		worker
		working
		workshop
		worried
		writer
		writing
		yesterday
		yourself"
	);

	final iHaveNoMouth = parseInput(
		"abcdefghijklmnopqrstuvwxyz h!@#$%^&* '\"-=_+`~;:()[]{}<>/\\?,.aealap aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
		20
		aaaaaaaaaaaaaaaaab
		aaaaaaaaaaaaaaaaac
		aaaaaaaaaaaaaaaaad
		aaaaaaaaaaaaaaaaaf
		aaaaaaaaaaaaaaaaag
		aaaaaaaaaaaaaaaaai
		aaaaaaaaaaaaaaaaak
		aaaaaaaaaaaaaaaaam
		aaaaaaaaaaaaaaaaan
		aaaaaaaaaaaaaaaaaq
		aaaaaaaaaaaaaaaaar
		aaaaaaaaaaaaaaaaas
		aaaaaaaaaaaaaaaaat
		aaaaaaaaaaaaaaaaau
		aaaaaaaaaaaaaaaaav
		aaaaaaaaaaaaaaaaaw
		aaaaaaaaaaaaaaaaax
		aaaaaaaaaaaaaaaaay
		aaaaaaaaaaaaaaaaaz
		help"
	);


}

